protocol: TCP
imagePullPolicy: Always
namespace: default
appName: frontend

replicaCount: 1

port: 3000

image:
  repository: vover173/webapp-docker
  tag: frontend
  pullPolicy: Always

service:
  name: frontend
  type: ClusterIP
  port: 80
  protocol: TCP

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: ''
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
  hosts:
    - host: 7test.com
      paths:
        - path: /
          pathType: Prefix
