apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: {{ .Values.backendName}}
  ports:
    - protocol: {{ .Values.service.protocol}}
      port: {{ .Values.port}}
      targetPort: {{ .Values.service.port}}