apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: {{ .Values.appName}}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.appName}}
  template:
    metadata:
      labels:
        app: {{ .Values.appName}}
    spec:
      containers:
      - name: {{ .Values.appName}}
        image: "{{ .Values.image.repository}}:{{ .Values.image.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy}}
        ports:
        - containerPort: {{ .Values.port}}
        env:
        - name: DB_HOST
          value: "{{ .Values.env.DB_HOST}}"
        - name: DB_PORT
          value: "{{ .Values.env.DB_PORT}}"
        - name: DB_USER
          value: "{{ .Values.env.DB_USER}}"
        - name: DB_PASS
          value: "{{ .Values.env.DB_PASS}}"
        - name: DB_NAME
          value: "{{ .Values.env.DB_NAME}}"